# Generated by Django 3.0.7 on 2020-07-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fueling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueling',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='fueling',
            name='date',
            field=models.DateField(verbose_name='fueling date'),
        ),
    ]
